const mediaItems = [
  { type: 'video', src: 'https://mrdlq3zu4lbpp4p1.public.blob.vercel-storage.com/Tilt_Table.mp4',            caption: 'Tilt Table' },
  { type: 'video', src: 'https://mrdlq3zu4lbpp4p1.public.blob.vercel-storage.com/Drone_Flight_Outdoor.mp4', caption: 'Outdoor Test Flight' },
  { type: 'video', src: 'https://mrdlq3zu4lbpp4p1.public.blob.vercel-storage.com/Music_Glove.mp4',           caption: 'Music Glove' },
  { type: 'video', src: 'https://mrdlq3zu4lbpp4p1.public.blob.vercel-storage.com/Drone_Flight_Indoor.mp4',  caption: 'Indoor Test Flight' },
  { type: 'video', src: 'https://mrdlq3zu4lbpp4p1.public.blob.vercel-storage.com/Cup_Car_Race.mp4',          caption: 'Cup Car Race' },

  { type: 'jpeg', src: 'https://mrdlq3zu4lbpp4p1.public.blob.vercel-storage.com/senior_design_show.jpg',        caption: 'Senior Design Showcase' },
  { type: 'jpeg', src: 'https://mrdlq3zu4lbpp4p1.public.blob.vercel-storage.com/senior_design_planterbox.jpg',  caption: 'Automatic Plantcare System – Hydroponic Plants' },
  { type: 'jpeg', src: 'https://mrdlq3zu4lbpp4p1.public.blob.vercel-storage.com/planterbox_circuit.jpg',        caption: 'Senior Design – Planterbox Circuit Test' },
  { type: 'jpeg', src: 'https://mrdlq3zu4lbpp4p1.public.blob.vercel-storage.com/planterbox_3d_print.jpg',       caption: 'Senior Design – 3D Printed Planterbox' },
  { type: 'jpeg', src: 'https://mrdlq3zu4lbpp4p1.public.blob.vercel-storage.com/senior_design_drone.jpg',       caption: 'ModiFly Design Team' },
  { type: 'jpeg', src: 'https://mrdlq3zu4lbpp4p1.public.blob.vercel-storage.com/lab_circuit_2.jpg',             caption: 'Circuit Design' },
  { type: 'jpeg', src: 'https://mrdlq3zu4lbpp4p1.public.blob.vercel-storage.com/lab_circuit_1.jpg',             caption: 'Signal Analysis' },
  { type: 'jpeg', src: 'https://mrdlq3zu4lbpp4p1.public.blob.vercel-storage.com/high_low_pass_filter.jpg',      caption: 'High & Low Pass Filter' },
  { type: 'jpeg', src: 'https://mrdlq3zu4lbpp4p1.public.blob.vercel-storage.com/embedded_system.jpg',           caption: 'Embedded Systems' },
  { type: 'jpeg', src: 'https://mrdlq3zu4lbpp4p1.public.blob.vercel-storage.com/microcomputers_ii.jpg',         caption: 'Microcomputers II' },
  { type: 'jpeg', src: 'https://mrdlq3zu4lbpp4p1.public.blob.vercel-storage.com/microcomputers_i.jpg',          caption: 'Microcomputers I' },
  { type: 'jpeg', src: 'https://mrdlq3zu4lbpp4p1.public.blob.vercel-storage.com/nsin_accelerator.jpg',          caption: 'NSIN Accelerator Program' },
  { type: 'jpeg', src: 'https://mrdlq3zu4lbpp4p1.public.blob.vercel-storage.com/drone_test_2.jpg',              caption: 'Flight Test 2' },
  { type: 'jpeg', src: 'https://mrdlq3zu4lbpp4p1.public.blob.vercel-storage.com/drone_test_1.jpg',              caption: 'Flight Test 1' },
  { type: 'jpeg', src: 'https://mrdlq3zu4lbpp4p1.public.blob.vercel-storage.com/drone_laptop.jpg',              caption: 'Laptop – Cockpit (Drone Pilot)' },
  { type: 'jpeg', src: 'https://mrdlq3zu4lbpp4p1.public.blob.vercel-storage.com/drone_gateway.jpg',             caption: 'Drone Gateway' },
  { type: 'jpeg', src: 'https://mrdlq3zu4lbpp4p1.public.blob.vercel-storage.com/drone_3d_print.jpg',            caption: 'Drone 3D Print Version 2' },
  { type: 'jpeg', src: 'https://mrdlq3zu4lbpp4p1.public.blob.vercel-storage.com/bse_2.jpg',                     caption: 'UTSA Main Campus' },
  { type: 'jpeg', src: 'https://mrdlq3zu4lbpp4p1.public.blob.vercel-storage.com/drone_cage.jpg',                caption: 'Outdoor Drone Cage – UTSA' },
  { type: 'jpeg', src: 'https://mrdlq3zu4lbpp4p1.public.blob.vercel-storage.com/drone_flight_controller.jpg',   caption: 'Version 1.0 Flight Controller' },
  { type: 'jpeg', src: 'https://mrdlq3zu4lbpp4p1.public.blob.vercel-storage.com/drone_1.jpg',                   caption: 'Drone Prototype Version 1.0' },
  { type: 'jpeg', src: 'https://mrdlq3zu4lbpp4p1.public.blob.vercel-storage.com/bes_1.jpg',                     caption: 'Biotechnology Science and Engineering Building – UTSA' },
  { type: 'jpeg', src: 'https://mrdlq3zu4lbpp4p1.public.blob.vercel-storage.com/custom_pc.jpg',                 caption: 'Custom Gaming PC Build' },
  { type: 'jpeg', src: 'https://mrdlq3zu4lbpp4p1.public.blob.vercel-storage.com/Micro1_Award.jpg',              caption: 'Microcomputer Systems I Award – 3rd Place' },
  { type: 'jpeg', src: 'https://mrdlq3zu4lbpp4p1.public.blob.vercel-storage.com/Micro2_Award.jpg',              caption: 'Microcomputer Systems II Award – 1st Place' },
];

export { mediaItems };